[package]
name = "rf256"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitflags = { version = "2.5.0", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
